### ISSUE TITLE
Opening a BPMN file from file explorer opens editor in VS Code, but SVG button is missing

### ISSUE THREAD

**Issue by mikewodarczyk** [kiegroup/kie-tooling-store#35]
If I double click a BPMN file on windows 10 in file explorer, it opens VS code and the graphical BPMN editor opens (cool!). But in the upper right corner where the export to SVG button belongs, there is only the split screen button.

The work around is to right click the file tab and select "reopen in text editor".
Then right click the text editor file tab and select "reopen in BPMN editor".
After doing this the SVG button is available next to the split screen button.  

By the way, this editor is really good.  I open these issues out of love.

**Comment by tiagobento** [comment]
Hi @mikewodarczyk! Thank you for taking the time to open these issues. It really helps us improve the Editors!

From the behaviour you described, seems like this is an issue with VS Code itself. To be sure, we'll investigate. If we confirm that this is on VS Code's side, we'll open an issue there too.

**Comment by tiagobento** [comment]
@mikewodarczyk Hi! I'm testing this again with VS Code 1.55.2. Looks like this is still happening, but only when opening a file from the explorer when VS Code is closed. If VS Code is open and you open the file from the explorer, the SVG button is there. Can you confirm that this is the case? Really looks like it's an issue on VS Code.

**Comment by Fjordo** [comment]
I correctly see the svg button in VS code 1.56.1
