### ISSUE TITLE
Shorcomings of DMN plugin in VSC

### ISSUE THREAD

**Issue by khush2704** [kiegroup/kie-tooling-store#37]
Hi, I want to know what all are the shorcomings or drawbacks of using DMN editor plugin in Visual Studio Code.
How can i check the validations of DMN model during compile time in VSCode , is it possible to check ? If yes, how ? Or its only possible during run time ?

**Comment by karreiro** [comment]
@khush2704,

The DMN editor VSCode plugin does not provide embedded validation, but you are able to validate your model and see eventual errors or warnings at the execution ([learn-dmn-in-15-minutes.com/learn/execution](https://learn-dmn-in-15-minutes.com/learn/execution)) phase.

We're planning to bring this kind of validation to the plugin soon tho :-)
