### ISSUE TITLE
Support condition expressions in sequence flows

### ISSUE THREAD

**Issue by clawoflight** [kiegroup/kie-tooling-store#39]
Hi, could you add support for actually writing condition expressions?

The UI is already almost there:
![image](https://user-images.githubusercontent.com/1181744/108855665-8a1e3f80-75e9-11eb-94ba-33f6308483d5.png)

I would like to be able to express the following:
```xml
<bpmn2:sequenceFlow id="SequenceFlow_1" name="eventName" sourceRef="Task_1" targetRef="ExclusiveGateway_2">
      <bpmn2:conditionExpression xsi:type="bpmn2:tFormalExpression" id="FormalExpression_1" language="http://www.example.com/language">some-expression</bpmn2:conditionExpression>
</bpmn2:sequenceFlow>
```

I can help, if provided some guidance :)

**Comment by ederign** [comment]
Moved to https://github.com/kiegroup/kogito-tooling/issues/429
