### ISSUE TITLE
Permit xml edit to diagrams

### ISSUE THREAD

**Issue by Fjordo** [kiegroup/kie-tooling-store#59]
The extension should be capable of letting the user modify the underlying xml code of a bpmn2 file.
A new button should be placed alog side the "show properties" and "show diagram" buttons, in the rigth top corner.

**Comment by tiagobento** [comment]
@Fjordo Hi! So for editing a BPMN file as text, you can use VS Code's "Open with.." menu. Then you can select "Text editor" and edit your file normally.

**Comment by Fjordo** [comment]
Hi, and thanks for the answer.
I know you can do that way but a shorcut would be interesting feature and a nice UX improvement.

**Comment by tiagobento** [comment]
@Fjordo Since VS Code already has this capability and we aim to be as integrated as possible with the platform, we won't be adding this capability for now. Thanks for the suggestion!
