### ISSUE TITLE
can not open bpmn file

### ISSUE THREAD

**Issue by rbaumgar** [kiegroup/kie-tooling-store#63]
Issue Type: <b>Bug</b>

try to open bpmn2 file
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

BPMN Editor 0.9.1
DMN Editor 0.9.1
Kogito Bundel 0.9.1
VSCode 1.56.2

Extension version: 0.9.1
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 4.18.0-240.22.1.el8_3.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 3451)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.00GB (1.52GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 5a57cda8-c6e3-418d-bc86-25900f90213f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30301612
vscorehovct:30302760
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by ederign** [comment]
hi @rbaumgar is it possible to share the bpmn file as a reproducer?

**Comment by rbaumgar** [comment]
I am not able to open any bpmn file! even after uninstall/install the plugins
here are some examples `https://github.com/kiegroup/kogito-examples/tree/stable/process-quarkus-example/src/main/resources/org/kie/kogito/examples`

**Comment by caponetto** [comment]
Hi @rbaumgar.
Can you please provide the info of your VS Code installation?
For that, open the VS Code and go to Help > About.

**Comment by rbaumgar** [comment]
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 4.18.0-240.22.1.el8_3.x86_64

**Comment by rbaumgar** [comment]
after another restart (without changing anything) of vscode, I am able to open bpmn2.
thx
