### ISSUE TITLE
can not support underline '_' or minus '-' with number in attribute ？!!!!

### ISSUE THREAD

**Issue by GitHubCuCu** [kiegroup/kie-tooling-store#67]
![image](https://user-images.githubusercontent.com/22938143/120172284-73653580-c235-11eb-9087-7cfc00ebeaac.png)

![image](https://user-images.githubusercontent.com/22938143/120172325-7d873400-c235-11eb-90c8-a77c790b379a.png)

**Comment by GitHubCuCu** [comment]
please help me

**Comment by manstis** [comment]
Hi, thank-you firstly for trying the editor. All feedback is most welcome.

I suspect we are being overly narrow in our parsing of attribute names in the predicate editor.

What we value most is peoples' opinion of using the text based expression editor for predicates. At the moment its implementation is largely incomplete as we did not want to spend a lot of effort on an area we really wanted feedback.

Whilst the PMML specification for predicates supports arbitrarily complex expressions the most complex we could find "in real life" was much more simple "range checks": i.e. `18 <= age <= 65` and the majority seem even more simple: `age >= 18`.

Can you provide any examples of the complexity of expression you need supported? It sure would help drive our direction.

**Comment by manstis** [comment]
See https://issues.redhat.com/browse/FAI-503

**Comment by GitHubCuCu** [comment]
our feature name like 'mv_3_0_24_1','person_3_0_isee_ml_103','la2_u_n' and 'codemodelcode_17_121'，arbitrarily complex expressions like "codemodelcode_17_121 > 2", but now our editor can not support '_' in feature name .

**Comment by GitHubCuCu** [comment]
'-' is also not support too; which separator can use?

**Comment by GitHubCuCu** [comment]
See https://issues.redhat.com/browse/FAI-503
------------------
thx for this, some users want to use the Editor interface to create their SCORECARD PMML model.

May I get how long or when this requirement are fulfilled？

**Comment by manstis** [comment]
ATM the expression editor only supports the regex `[a-zA-Z]+[0-9]*` i.e. `field` or `field123` or `FIELD` etc.

I am working on FAI-503 at the moment; however only because it is a simple fix. General development of the editor is suspended until we get sufficient feedback to warrant the investment of time. Small, simple fixes will no doubt continue but more substantial development would need to be planned and resourced accordingly.

**Comment by manstis** [comment]
I have submitted a [fix](https://github.com/kiegroup/kogito-tooling/pull/520) for review and merge.

When it becomes available after merge depends on _where_/_how_ you are using the editor. Can you advise?

VSCode plugin? http://scorecard.new etc.

**Comment by GitHubCuCu** [comment]
yes, I use VSCode plugin.
thx!!!!

**Comment by manstis** [comment]
OK; @ederign @tiagobento can you please advise the release schedule?

Clearly the PR will need approval and merge first.

**Comment by GitHubCuCu** [comment]
there is another question：minus '-' with number is also not support?
![image](https://user-images.githubusercontent.com/22938143/120582128-8e66be00-c45e-11eb-8a25-5e1be7a5419a.png)
![image](https://user-images.githubusercontent.com/22938143/120582280-c8d05b00-c45e-11eb-96eb-4f191e87afdf.png)

**Comment by manstis** [comment]
The same fix I submitted should resolve that too.

**Comment by GitHubCuCu** [comment]
> The same fix I submitted should resolve that too.

thx!!!!❤

**Comment by manstis** [comment]
The issues reported under this issue have all been fixed by https://github.com/kiegroup/kogito-tooling/pull/520
- use of `_` in attribute field names
- use of `-` in attribute field names
- use of `-` in right hand side operands

**Comment by GitHubCuCu** [comment]
thx!!! please, when a little complex expressions like  i.e. 18 <= age <= 65  can support ?
![image](https://user-images.githubusercontent.com/22938143/120616114-87a27000-c48b-11eb-8c30-6cc7ce23c90a.png)
