### ISSUE TITLE
when edit data dictionary, the expression（like fea_01 > 2 and fea_01 < 3) not change with new name !

### ISSUE THREAD

**Issue by GitHubCuCu** [kiegroup/kie-tooling-store#69]
![image](https://user-images.githubusercontent.com/22938143/121042418-404b1500-c7e6-11eb-98d5-7deffedcd702.png)
#67

**Comment by ederign** [comment]
@GitHubCuCu thanks for reporting this! @manstis when you have a chance, could you please take a look at this?

**Comment by manstis** [comment]
Thank-you @GitHubCuCu.

I've logged the issue https://issues.redhat.com/browse/FAI-519.

It seems to only affect "composite predicates" i.e. those with AND or OR within them.

**Comment by manstis** [comment]
See https://github.com/kiegroup/kogito-tooling/pull/540

When that is merged I'll close this issue.

**Comment by manstis** [comment]
PR has been merged. This is fixed in the next release.

FYI @ederign @tiagobento

**Comment by ederign** [comment]
This will be incorporated on the 0.11.0 release!
